### ISSUE TITLE
#base语句支持

### ISSUE THREAD

**Issue by tontyoutoure** [zombieJ/nw-dota2editor#1]
您好，请问能否支持一下 #base 语句，编辑器能够无视txt文件中的这些语句也好，当前版本中 #base语句保存后会被自动删除。

**Comment by zombieJ** [comment]
@tontyoutoure ， 有个v2版本还在开发中： https://github.com/zombieJ/MatrixEditor

**Comment by tontyoutoure** [comment]
可以可以 加油老铁
